#!/bin/bash

img="$1"
n="$2"
s=$(($(ls -1 "./imgs" | wc -l) - 1))
lab=$(grep -e "^${img},.*" "./imgs/label.csv" | sed -e 's/^'"$img"',\(.*\)/\1/g')
for ((i = 0; i < n; ++i)); do
	cp "./imgs/${img}.png" "./imgs/$((s + i)).png"
	echo "$((s + i)),${lab}" >>./imgs/label.csv
done
